export const NASCAR_25_TRACKS = [
  'Atlanta Motor Speedway',
  'Bristol Motor Speedway',
  'Charlotte Motor Speedway',
  'Charlotte Road Course',
  'Chicago Street Course',
  'Circuit of the Americas',
  'Darlington Raceway',
  'Daytona International Speedway',
  'Dover Motor Speedway',
  'EchoPark Speedway',
  'Homestead-Miami Speedway',
  'Indianapolis Motor Speedway',
  'Indianapolis Road Course',
  'Iowa Speedway',
  'Kansas Speedway',
  'Las Vegas Motor Speedway',
  'Lime Rock Park',
  'Lucas Oil Indianapolis Raceway Park',
  'Martinsville Speedway',
  'Michigan International Speedway',
  'Nashville Superspeedway',
  'New Hampshire Motor Speedway',
  'North Wilkesboro Speedway',
  'Phoenix Raceway',
  'Pocono Raceway',
  'Richmond Raceway',
  'Rockingham Speedway',
  'Sonoma Raceway',
  'Talladega Superspeedway',
  'Texas Motor Speedway',
  'Watkins Glen International',
  'World Wide Technology Raceway',
];

export const NASCAR_2025_CUP_SCHEDULE = [
  'Daytona International Speedway',
  'Atlanta Motor Speedway',
  'Circuit of the Americas',
  'Phoenix Raceway',
  'Las Vegas Motor Speedway',
  'Homestead-Miami Speedway',
  'Martinsville Speedway',
  'Darlington Raceway',
  'Bristol Motor Speedway',
  'Talladega Superspeedway',
  'Texas Motor Speedway',
  'Kansas Speedway',
  'Charlotte Motor Speedway',
  'Nashville Superspeedway',
  'Michigan International Speedway',
  'Pocono Raceway',
  'EchoPark Speedway',
  'Chicago Street Course',
  'Sonoma Raceway',
  'Dover Motor Speedway',
  'Indianapolis Motor Speedway',
  'Iowa Speedway',
  'Watkins Glen International',
  'Richmond Raceway',
  'Daytona International Speedway',
  'Darlington Raceway',
  'World Wide Technology Raceway',
  'Bristol Motor Speedway',
  'New Hampshire Motor Speedway',
  'Kansas Speedway',
  'Charlotte Road Course',
  'Las Vegas Motor Speedway',
  'Talladega Superspeedway',
  'Martinsville Speedway',
  'Phoenix Raceway',
];
